---
title: "R Notebook"
output: html_notebook
---

```{r}


Sys.setlocale(category = "LC_ALL", locale = "chs")

library(tidyverse)
```


```{r}

sales %>% colnames()
```



```{r}

sales %>% 
  mutate(firm = 企业简称,
            past_sales = `1月基准销售金额`,
            past_eq = `1月基准权益销售金额`, 
            past_area = `1月基准销售面积`,
            cur_sales = if_else(is.na(`2月企业提供销售金额`), `2月单月预估销售金额`, `2月企业提供销售金额`),
            eq_ratio = `2月基准权益比例`,
            price = `2月基准销售均价`,
            # cur_eq = if_else(is.na(`2月企业提供权益销售`), cur_sales*eq_ratio,`2月企业提供权益销售`),
            # cur_area = if_else(is.na(`2月企业提供销售面积`), cur_sales/price, `2月企业提供销售面积`),
            cur_eq = `2月企业提供权益销售`,
            cur_area = `2月企业提供销售面积`,
            total_sales = if_else(is.na(`1-2月企业提供销售金额`), cur_sales + past_sales, `1-2月企业提供销售金额`),
            total_eq = case_when(
               !is.na(`1-2月企业提供权益销售`) ~ `1-2月企业提供权益销售`,
               !is.na(cur_eq) ~ past_eq + cur_eq,
               TRUE ~ total_sales * eq_ratio),
            total_area = case_when(
              !is.na(`1-2月企业提供销售面积`) ~ `1-2月企业提供销售面积`,
              !is.na(cur_area) ~ cur_area + past_area,
              TRUE ~  total_sales/price)
            ) %>% 
  select(firm, starts_with("total"), starts_with("cur")) ->df
```


```{r}

df %>% write_excel_csv("df.csv")
```



```{r}

library(magick)

image_read("../header.jpg") -> header
footer <- image_read("../footer.jpg")



showtext::showtext.auto()
showtext::showtext.opts(dpi = 300)
month <- lubridate::month(Sys.Date())
tibble(x = 0, y = 0, t = str_glue("1-{month}月中国房地产企业销售金额TOP100")) %>% 
ggplot(aes(x, y)) + 
  geom_text(aes(label = t), col = "#605742") + theme_void() + 
  theme(text = element_text(face = "bold"))
ggsave("name.png")


image_read("name.png") %>% 
  image_trim() %>% 
  image_transparent(color = "white") %>% 
  image_scale("500x") %>% 
  image_composite(
    header, composite_image = ., offset = "+50+220"
  )



tibble(x = 0, y = 0, t = "统计来源：观点指数") %>% 
ggplot(aes(x, y)) + 
  geom_text(aes(label = t), col = "#605742") + theme_void()
ggsave("source.png")

(lubridate::ymd(str_glue("2020-{month + 1}-01"))-1) %>% str_split("-", simplify = TRUE) -> dates


tibble(x = 0, y = 0, 
       t = str_glue("统计日期：2020年1月1日-{dates[2] %>% str_remove('^0')}月{dates[3]}日")) %>% 
ggplot(aes(x, y)) + 
  geom_text(aes(label = t), col = "#605742") + theme_void()
ggsave("dates.png")

image_read("source.png") %>% 
  image_trim() %>% 
  image_transparent(color = "white") %>% 
  image_scale("x14") %>% 
  image_composite(
    footer, composite_image = ., offset = "+350+55"
  ) -> temp
  
image_read("dates.png") %>% 
  image_trim() %>% 
  image_transparent(color = "white") %>% 
  image_scale("x14") %>% 
  image_composite(
    temp, composite_image = ., offset = "+350+30"
) 




```




```{r}

df %>% select(firm, total_area) %>% 
ggtexttable(rows = NULL, 
            theme = ttheme(base_colour = "gray50",
              colnames.style = colnames_style(size = 8, color = "white",
                fill = "#f3a06e", linewidth = 0.3),
              padding = unit(c(8, 3), "mm"), base_size = 14, 
              tbody.style = tbody_style(size = 8,
                                  fill = c("#f4d5b1", "#eeeded"),
                                  color = "gray10", face = "plain",
                                  linewidth = 0.3)
            )) + theme(text = element_text(family = "source-han-sans-cn")) -> g

image_read("../imgs.png")->img
cross_df(list(y = c(1:3), x = 1:10)) %>% 
  mutate(t = "观点指数研究院") %>% 
  ggplot(aes(x, y)) + 
  geom_text(aes(label = t), angle = 135, size = 2, color = "#b8b4ad") +
  ylim(c(-1,10)) +
  theme_void()
showtext::showtext_auto()
ggsave("marks.png", )


logo <- image_read("https://www.r-project.org/logo/Rlogo.png")
img <- image_trim(image_read("../tbl.png"))
image_ch

img %>% 
image_annotate("汇总")

# image_read("E:/saler/dev/mask_.png") %>% 
#   image_transparent("white")-> mask
# img  

img

imgs <- c(img, mask)

image_flatten(imgs, "Multiply")
# image_trim() %>% image_rotate(90) %>% 
  image_composite(img, composite_image = .)
```


```{r}
mask %>%
  image_trim() %>% 
  image_scale("800x") -> scaled_mask

image_append(rep(scaled_mask, 8), stack = TRUE) %>% 
    image_border(geometry = "50x60", color = "white")-> large_mask


large_mask %>% image_write("mask.png")

mask <- image_read("mask.png")
image_flatten(c(image_trim(img), mask), "Multiply")
```




```{r}
pydf %>% 
  mutate(firm = replace(firm, firm == "奥园控股", "奥园集团"))
  mutate(py = replace(py, py == "askg", "asjt")) -> pydf
```


```{r}
db <- mongo(collection = "saler", db = "saler", 
              url = "mongodb+srv://saler:5al3r@cluster-opuen.mongodb.net/test?retryWrites=true&w=majority", 
              verbose = FALSE)

df <- db$find() %>% mutate_at(vars(-firm), as.numeric) %>% 
     
     mutate(cur_sales = case_when(
                  adj_sale != 0 ~ adj_sale,  
                  sale_firm != 0 ~ sale_firm,
                  TRUE ~ cur_preds),
            cur_eq = if_else(adj_eq == 0, eq_firm, adj_eq),
            cur_area = if_else(adj_area == 0, area_firm, adj_area),
            
            total_sales = case_when(
                    cum_adj_sale != 0 ~ cum_adj_sale,
                    cum_sale != 0 ~ cum_sale,
                    TRUE ~ cur_sales + past_sales),
            total_eq = case_when(
              cum_adj_eq != 0 ~ cum_adj_eq,
              cum_eq != 0 ~ cum_eq,
              cur_eq != 0 ~ past_eq + cur_eq,
              TRUE ~ total_sales * eq_ratio),
            total_area = case_when(
              cum_adj_area != 0 ~ cum_adj_area,
              cum_area != 0 ~ cum_area,
              cur_area != 0 ~ cur_area + past_area,
              TRUE ~  total_sales/price),
            source = case_when(
              (cum_adj_eq + cum_adj_sale + cum_adj_area + adj_eq + adj_sale + adj_area) > 0 ~ "指数调整",
              (cum_eq + cum_sale + cum_area + eq_firm + sale_firm + area_firm) > 0 ~ "公司提供",
              TRUE ~ "指数预测")
     ) %>% 
     select(firm, starts_with("total"), starts_with("cur"), source) %>% 
     left_join(pydf, by = "firm") %>% 
     mutate_at(vars(starts_with("total")), ~ round(.x, 1))

 df %>% 
  arrange(desc(total_sales), py) %>% 
  slice(1:100) %>% 
  bind_cols(rank = 1:100) %>% 
  transmute(`排名` = rank, `公司名称` = firm, `累计全口径销售（亿元）` = round(total_sales, 1))
```









